name: mobile_ap
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^3.12.1
  flutter_svg: ^2.0.17
  firebase_auth: ^5.5.1
  flutter_launcher_icons: ^0.14.3
  cloud_firestore: ^5.6.5
  cached_network_image: ^3.3.0
  carousel_slider: ^5.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon.png"
    # Ensure this path is correct and the file exists

flutter:
  uses-material-design: true
  assets:
    - assets/logo.svg
    - assets/gift_banner.PNG
    
