// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCDSNGnai5s3fwxNlytcQlIr-USf8Z7_4k',
    appId: '1:839031885713:web:2c155e12a8441157bc1430',
    messagingSenderId: '839031885713',
    projectId: 'dream-4d098',
    authDomain: 'dream-4d098.firebaseapp.com',
    storageBucket: 'dream-4d098.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCuHh3iUfQaRD5L3dYjDahcd0prVHjJet0',
    appId: '1:839031885713:android:2926d7fc7c929eacbc1430',
    messagingSenderId: '839031885713',
    projectId: 'dream-4d098',
    storageBucket: 'dream-4d098.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC2NijsoT-hwsLRL9A3Z5ixJtNqrkkbu-s',
    appId: '1:839031885713:ios:0a9172d3bd47d332bc1430',
    messagingSenderId: '839031885713',
    projectId: 'dream-4d098',
    storageBucket: 'dream-4d098.firebasestorage.app',
    iosClientId: '839031885713-bd4oudf63pneu1g4pvpsstbiv298ep7a.apps.googleusercontent.com',
    iosBundleId: 'com.example.mobileAp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC2NijsoT-hwsLRL9A3Z5ixJtNqrkkbu-s',
    appId: '1:839031885713:ios:0a9172d3bd47d332bc1430',
    messagingSenderId: '839031885713',
    projectId: 'dream-4d098',
    storageBucket: 'dream-4d098.firebasestorage.app',
    iosClientId: '839031885713-bd4oudf63pneu1g4pvpsstbiv298ep7a.apps.googleusercontent.com',
    iosBundleId: 'com.example.mobileAp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCDSNGnai5s3fwxNlytcQlIr-USf8Z7_4k',
    appId: '1:839031885713:web:e15450e63467647cbc1430',
    messagingSenderId: '839031885713',
    projectId: 'dream-4d098',
    authDomain: 'dream-4d098.firebaseapp.com',
    storageBucket: 'dream-4d098.firebasestorage.app',
  );
}
